services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev
